#!/usr/bin/env bash

#====================== SYSTEM ======================
# 设置默认编辑器
if command -v nvim &> /dev/null; then
  export EDITOR=nvim
  export VISDL=nvim
else
  export EDITOR=vim
  export VISDL=vim
fi


# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1;


#======================  LESS  ======================
# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';


#====================== PYTONE ======================
# cannot use pip unless inside virtual env
export PIP_REQUIRE_VIRTUALENV=true;

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';


#======================  RPG   ======================
# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);


#======================  NVM   ======================
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
