#!/usr/bin/env bash

#====================== SYSTEM ======================
# 设置默认编辑器
if command -v nvim &>/dev/null; then
  export EDITOR=nvim
  export VISDL=nvim
else
  export EDITOR=vim
  export VISDL=vim
fi

# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth'

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1

#======================  LESS  ======================
# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}"

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X'

#====================== PYTONE ======================
# cannot use pip unless inside virtual env
export PIP_REQUIRE_VIRTUALENV=true

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8'

#======================  RPG   ======================
# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty)

#======================  NVM   ======================
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

#======================  PNPM  ======================

uNames=$(uname -s)
osName=${uNames:0:5}
if [[ "$osName" == "Darwi" ]]; then
  # Mac系统
  export PNPM_HOME="${HOME}/Library/pnpm"
elif [[ "$osName" == "Linux" ]]; then
  # Linux系统
  export PNPM_HOME="/home/admin/.local/share/pnpm"
fi

if [ -n "$PNPM_HOME" ]; then
  case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
  esac
fi

#======================  FIG   ======================
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"

#====================== Flutter ======================
if [[ "$osName" == "Darwi" ]]; then
  # Mac系统
  export PATH="$HOME/development/flutter/bin:$PATH"
  export PATH="$HOME/.gem/bin:$PATH"
elif [[ "$osName" == "Linux" ]]; then
  # Linux系统
  FNM_PATH="/home/$USER/.local/share/fnm"
  if [ -d "$FNM_PATH" ]; then
    export PATH="/home/$USER/.local/share/fnm:$PATH"
    eval "`fnm env`"
  fi
fi
