[tools]
node = "24"
"npm:corepack" = "latest"
"npm:czg" = "latest"
helm = "latest"
usage="latest"
openbao="latest"
claude-code="latest"
"npm:ctx7" = "latest"
kubectl = "latest"
tmux = "latest"
"pipx:tmuxp" = "latest"
gh = "latest"
ripgrep = "latest"
"npm:@playwright/mcp" = "latest"
postgres = "17"

[settings]
# 自动检测 .node-version 文件来设置 Node.js 版本
idiomatic_version_file_enable_tools = ["node"]
